version: '3.3'
volumes:
  app: ~
  node_modules: ~

services:
  nuxt-3-fnet-ios:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    image: fnet_ios
    container_name: fnet_ios
    command: pnpm run dev
    working_dir: /app
    tty: true
    volumes:
      - type: bind
        source: C:\MyProject\fNet-payment-api-nuxt
        target: /app
        bind:
          create_host_path: true
        user: '1000:1000'
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - '3000:3000'
